[[language]]
name = "python"
language-servers = ["ty"]

[language-server.ty]
command = "ty"
args = ["check"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "nix"
language-servers = ["nil"]

[language-server.nil]
command = "nil"

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"

