inherits = "catppuccin_mocha"

"ui.background" = {}

"comment" = { fg = "overlay2", modifiers = [] }
"variable.parameter" = { fg = "maroon", modifiers = [] }
"keyword.control.conditional" = { fg = "mauve", modifiers = [] }
"namespace" = { fg = "yellow", modifiers = [] }

"markup.bold" = { fg = "red", modifiers = [] }
"markup.italic" = { fg = "red", modifiers = [] }
"markup.link.url" = { fg = "blue", modifiers = [] }

"ui.statusline" = { fg = "subtext1", bg = "#00000000" }
"ui.statusline.inactive" = { fg = "surface1", bg = "#00000000" }
"ui.linenr" = { fg = "overlay0" }

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
